# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FAN.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FON = QtWidgets.QLabel(self.centralwidget)
        self.FON.setGeometry(QtCore.QRect(0, -10, 961, 561))
        self.FON.setText("")
        self.FON.setPixmap(QtGui.QPixmap("W9dC.gif"))
        self.FON.setObjectName("FON")
        self.ACTIV = QtWidgets.QPushButton(self.centralwidget)
        self.ACTIV.setGeometry(QtCore.QRect(0, 250, 951, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.ACTIV.setFont(font)
        self.ACTIV.setStyleSheet("border:none;\n"
"\n"
"\n"
"color: rgb(0, 2, 158);")
        self.ACTIV.setText("")
        self.ACTIV.setIconSize(QtCore.QSize(10, 15))
        self.ACTIV.setShortcut("")
        self.ACTIV.setAutoRepeat(False)
        self.ACTIV.setAutoExclusive(False)
        self.ACTIV.setObjectName("ACTIV")
        self.NOVA = QtWidgets.QLabel(self.centralwidget)
        self.NOVA.setGeometry(QtCore.QRect(0, 0, 961, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NOVA.setFont(font)
        self.NOVA.setStyleSheet("color: rgb(255, 0, 0);")
        self.NOVA.setObjectName("NOVA")
        self.ILIA = QtWidgets.QLabel(self.centralwidget)
        self.ILIA.setGeometry(QtCore.QRect(0, 380, 951, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ILIA.setFont(font)
        self.ILIA.setStyleSheet("color: rgb(28, 202, 255);")
        self.ILIA.setObjectName("ILIA")
        self.an = QtWidgets.QPushButton(self.centralwidget)
        self.an.setGeometry(QtCore.QRect(210, 250, 551, 51))
        self.an.setStyleSheet("border:none;")
        self.an.setText("")
        self.an.setObjectName("an")
        self.FON.raise_()
        self.NOVA.raise_()
        self.ILIA.raise_()
        self.ACTIV.raise_()
        self.an.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ACTIV.setToolTip(_translate("MainWindow", "<html><head/><body><p>dzf</p></body></html>"))
        self.ACTIV.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0d2298;\">eva</span></p></body></html>"))
        self.NOVA.setText(_translate("MainWindow", "FUN:"))
        self.ILIA.setText(_translate("MainWindow", "ВЫ:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
